### ISSUE TITLE
How to save the forest in python

### ISSUE THREAD

**Issue by earlfernando** [neurodata/SPORF#307]
How do you save the forest in python , Im unable to save it using pickle. Is there any other method to do it?

**Comment by falkben** [comment]
Unfortunately, that is not currently an option, as our our forests exist in C++ and the object returned is not pickleable.  We'll need to implement our own pickle method.  It is an option we would like to support.

**Comment by pepetikesavasiddhardha** [comment]
Yes I am working on a project and I want to save the trained rerf classifier model but I am unable to do it with general pickling methods like using joblib or pickle library and I am getting an error of this kind
**TypeError: cannot pickle 'pyfp.fpForest' object**
Can someone @falkben please help me how can I save the trained model so that it can be loaded when ever we need to test on a test dataset. This is very important for our project. Please help me in over coming this issue
